#!/bin/sh

if [ $# -lt 3 ]; then
    echo "Usage: $0 <redirection server IP> <redirection server port> <command> [arguments]"
    exit 2
fi

if [ "$1" = "original" ]; then
    NETREDIRECT_HOST=""
else
    NETREDIRECT_HOST="$1"
fi

if [ "$2" = "original" ]; then
    NETREDIRECT_PORT=""
else
    NETREDIRECT_PORT="$2"
fi

export NETREDIRECT_HOST NETREDIRECT_PORT
export LD_PRELOAD="libnetredirect.so"

shift 2
exec $@
