#!/bin/sh

if [ $# -lt 3 ]; then
    echo "Usage: $0 <redirection server IP> <redirection server port> <command> [arguments]"
    exit 2
fi

export NETREDIRECT_HOST="$1"
export NETREDIRECT_PORT="$2"
export LD_PRELOAD="libnetredirect.so"

shift 2
exec $@
